[build]
  command = "bash build.sh"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"
